### PR TITLE
Minor fixes to the EQL guide

### PR DESCRIPTION
**Pull request by cavokz**
While reading I found some possible minor EQL documentation issues. I started accumulating their fixes here so that I won't forget any.

I'm not done with the reading but please check if any of my commits is actually not right already.

BTW, is this the right place for them? :)

### CODE REVIEW

**Comment by rw-access** [comment]
Thanks @cavokz.
This is the right place if you're referring to the docs for Endgame EQL and the python `eql` package.

FYI. We made some changes to the language in [Elasticsearch EQL](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/eql.html), and that's where the language itself is going. I won't make any breaking changes to Endgame or this repo, but might make some "opt-in".

**Comment by cavokz** [comment]
@rw-access, thanks for the heads up. My goal is to understand a bit more in depth what you can do with EQL, no special need of it right now.

I see that in the new docs substring does not need the fix and that the subtract function is not even there (is it on purpose?).

I'm wondering if it does make any sense to fix the legacy EQL guide then.

**Comment by rw-access** [comment]
We still maintain it, just don't actively develop new features here, so your changes are still welcome.

**Comment by rw-access** [comment]
These changes LGTM. Let me know when you're ready to merge, and remove WIP and I'll merge the PR

**Comment by cavokz** [comment]
I finished with the reading (skipped the Python api part), did not find anything else.

@rw-access feel free to merge.

**Review by rw-access — APPROVED** [review]

**Pull request merged**
