### PR TITLE
Add regex/regex~, like/like~ and func~()

### LINKED ISSUE #50: Add like/regex and insensitive functions behind Elasticsearch flag
Related to https://github.com/elastic/elasticsearch/issues/68639

When in `eql.parser.elasticsearch_syntax` mode
* `like` and `regex` syntax should be recognized
* insensitive functions (trailing `~`) should be recognized
* `in~` should be recognized
* `=~`, `!~` shouldn't be recognized (yet)

Otherwise, the above should recognized as invalid syntax

### PR DESCRIPTION
**Pull request by rw-access**
## Issues
Closes #50 

## Details
Added `regex`, `regex~`, `like`, `like~` and `function~(...)` syntax. The PythonEngine functionality remains unchanged since there are no AST-side changes.

Here are the error messages. In Elasticsearch mode:
```
Process finished with exit code 0
Error at line:1,column:31
Invalid syntax
process where process_name :  length()
                              ^^^^^^
Error at line:1,column:15
Expected string not number
process where pid : 1
              ^^^
Error at line:1,column:15
Expected string not number
process where pid like 1
              ^^^
Error at line:1,column:15
Expected string not number
process where pid regex 1
              ^^^
Error at line:1,column:15
Expected string not number
process where pid like~ 1
              ^^^
Error at line:1,column:15
Expected string not number
process where pid regex~ 1
              ^^^
Error at line:1,column:28
Invalid syntax. Compare with == instead of =
process where process_name = "cmd.exe"
                           ^
Error at line:1,column:31
Invalid string literal. Use " or """ based strings.
process where process_name == 'cmd.exe'
                              ^^^^^^^^^
Error at line:1,column:31
Invalid string literal. Use " or """ based strings.
process where process_name == ?'cmd.exe'
                              ^^^^^^^^^^
Error at line:1,column:31
Invalid string literal. Use " or """ based strings.
process where process_name == ?"cmd.exe"
                              ^^^^^^^^^^

```

In Endgame parsing mode (default)
```
Error at line:1,column:31
Invalid syntax
process where process_name :  length()
                              ^^^^^^
Error at line:1,column:34
Invalid syntax
process where process_name like  length()
                                 ^^^^^^
Error at line:1,column:31
Invalid string literal
process where process_name == """cmd.exe"""
                              ^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: wildcard(process_name, "cmd.exe")
process where process_name : "cmd.exe"
              ^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: wildcard(process_name, "cmd.exe")
process where process_name : ("cmd.exe")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:31
Invalid syntax
process where process_name :  length()
                              ^^^^^^
Error at line:1,column:31
Invalid string literal
process where process_name == """cmd.exe"""
                              ^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Explicit case-insensitivity is not supported.
process where process_name in~ ("cmd.exe")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: wildcard(process_name, "cmd.exe")
process where process_name like "cmd.exe"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: wildcard(process_name, "cmd.exe")
process where process_name like ("cmd.exe")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: wildcard(process_name, "cmd.exe")
process where process_name like~ "cmd.exe"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: wildcard(process_name, "cmd.exe")
process where process_name like~ ("cmd.exe")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: match(process_name, "cmd.exe")
process where process_name regex~ ("cmd.exe")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: match(process_name, "cmd.exe")
process where process_name regex "cmd.exe"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: match(process_name, "cmd.exe")
process where process_name regex ("cmd.exe")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: match(process_name, "cmd.exe")
process where process_name regex~ "cmd.exe"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Try: match(process_name, "cmd.exe")
process where process_name regex~ ("cmd.exe")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error at line:1,column:15
Invalid syntax. Explicit case-insensitivity is not supported
process where startsWith~(process_name, "cmd.exe")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### CODE REVIEW

**Review by brokensound77 — APPROVED** [review]
👍 nice update

is regex already limited to lucene style regex?

**Comment by rw-access** [comment]
In Python/Endgame, the regex syntax isn't very well defined. For the `regex`/ `regex~` predicates, it only validates that it's a string and not that it's valid Lucene regex. If we find that's not enough, we can add more validation.

**Comment by brokensound77** [comment]
> In Python/Endgame, the regex syntax isn't very well defined. For the `regex`/ `regex~` predicates, it only validates that it's a string and not that it's valid Lucene regex. If we find that's not enough, we can add more validation.

Will eql-es regex always be limited to lucene regex? How stable is lucene regex? If it is not too heavy of a lift, I think the validation could go a long way, especially since regex can easily get convoluted, it would help rule reviewers. If so, it could make sense to do it in a separate PR

**Comment by rw-access** [comment]
Pretty stable, although I hope 8.0 turns invalid escapes into a hard error. Because until that happens, we cant do `\w` or `\d`.

And agree, there's definitely value and I'll make a follow up PR eventually validate the regex syntax.

**Pull request merged**
